<?xml version="1.0"?>

<robot name="spot_cam_payload" xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:property name="spot_cam_base_length" value="0.32"/>
  <xacro:property name="spot_cam_base_width" value="0.19"/>
  <xacro:property name="spot_cam_base_height" value="0.09"/>

  <xacro:property name="spot_cam_housing_radius" value="${0.135/2.0}"/>
  <xacro:property name="spot_cam_housing_height" value="0.15"/>


  <xacro:macro name="spot_cam_payload">
    <joint name="spot_cam_payload_joint" type="fixed">
      <origin xyz="${0.16 - spot_cam_base_length/2.0} 0.0 ${spot_cam_base_height/2.0}" rpy="0 0 0"/>
      <parent link="front_rail"/>
      <child link="spot_cam_link"/>
    </joint>

    <link name="spot_cam_link">

      <xacro:inertial_cuboid_with_pose mass="1" x_length="${spot_cam_base_length}" y_length="${spot_cam_base_width}" z_length="${spot_cam_base_height}">
        <origin xyz="0 0 0" rpy="0 0 0"/>
      </xacro:inertial_cuboid_with_pose>

      <!-- Camera base -->
      <visual>
        <geometry>
          <box size="${spot_cam_base_length} ${spot_cam_base_width} ${spot_cam_base_height}"/>
        </geometry>
        <material name="LightGray">
          <color rgba="0.5 0.5 0.5 1"/>
        </material>
      </visual>
      <collision>
        <geometry>
          <box size="${spot_cam_base_length} ${spot_cam_base_width} ${spot_cam_base_height}"/>
        </geometry>
      </collision>

      <!-- Cam housing -->
      <visual>
        <origin xyz="${-0.16 + spot_cam_base_length/2.0 + 0.14 - spot_cam_housing_radius} 0.0 ${-spot_cam_base_height/2 + spot_cam_housing_height/2.0}" rpy="0.0 0.0 0.0"/>
        <geometry>
          <cylinder length="${spot_cam_housing_height}" radius="${spot_cam_housing_radius}"/>
        </geometry>
        <material name="LightGray">
          <color rgba="0.5 0.5 0.5 1"/>
        </material>
      </visual>

      <collision>
        <origin xyz="${-0.16 + spot_cam_base_length/2.0 + 0.14 - spot_cam_housing_radius} 0.0 ${-spot_cam_base_height/2 + spot_cam_housing_height/2.0}" rpy="0.0 0.0 0.0"/>
        <geometry>
          <cylinder length="${spot_cam_housing_height}" radius="${spot_cam_housing_radius}"/>
        </geometry>
      </collision>
    </link>

  </xacro:macro>
</robot>
