<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">
    <xacro:include filename="$(find hector_xacro_tools)/urdf/joint_macros.urdf.xacro" />

    <xacro:macro name="spot_leg" params="leg_name" >

      
        <xacro:property name="base_to_hip_xyz"            value="${front * base_to_hip_x} ${left * base_to_hip_y} 0" />
        <xacro:property name="hip_to_upper_leg_xyz"       value="0 ${left * hip_to_upper_leg_y} 0" />

        <link name="${leg_name}_hip">
            <visual>
                <geometry>
                    <mesh filename="package://hector_spot_description/meshes/${leg_name}_hip.dae" />
                </geometry>
            </visual>
            <collision>
                <geometry>
                    <mesh filename="package://hector_spot_description/meshes/${leg_name}_hip_collision.stl" /> <!-- TODO replace with primitive -->
                </geometry>
            </collision>
            <inertial>
                <mass value="${hip_mass}"/>
                <inertia ixx="${(1/12) * hip_mass * (hip_width * hip_width + hip_height * hip_height)}" ixy="0.0" ixz="0.0"
                            iyy="${(1/12) * hip_mass * (hip_length * hip_length + hip_height * hip_height)}" iyz="0.0"
                            izz="${(1/12) * hip_mass * (hip_length * hip_length + hip_width * hip_width)}" />     
            </inertial>
        </link>
        
        <joint name="${leg_name}_hip_x" type="revolute">
            <origin xyz="${base_to_hip_xyz}" rpy="0 0 0" />
            <axis xyz="1 0 0" />
            <parent link="body" />
            <child link="${leg_name}_hip" />
            <limit effort="80" velocity="15" lower="-0.78539816339744827899" upper="0.78539816339744827899" />
        </joint>
        
        <link name="${leg_name}_upper_leg">
            <visual>
                <geometry>
                    <mesh filename="package://hector_spot_description/meshes/${leg_name}_upper_leg.dae" />
                </geometry>
            </visual>
            <collision>
                <geometry>
                    <mesh filename="package://hector_spot_description/meshes/${leg_name}_upper_leg_collision.stl" /> <!-- TODO replace with primitive -->
                </geometry>
            </collision>
            <inertial>
                <origin xyz="0 0 -0.14" rpy="0 0 0" />
                <mass value="${upper_leg_mass}"/>
                <inertia ixx="${(1/12) * upper_leg_mass * (upper_leg_width * upper_leg_width + upper_leg_height * upper_leg_height)}" ixy="0.0" ixz="0.0"
                            iyy="${(1/12) * upper_leg_mass * (upper_leg_length * upper_leg_length + upper_leg_height * upper_leg_height)}" iyz="0.0"
                            izz="${(1/12) * upper_leg_mass * (upper_leg_length * upper_leg_length + upper_leg_width * upper_leg_width)}" />     
            </inertial>
        </link>
        
        <joint name="${leg_name}_hip_y" type="revolute">
            <origin xyz="${hip_to_upper_leg_xyz}" rpy="0 0 0" />
            <axis xyz="0 1 0" />
            <parent link="${leg_name}_hip" />
            <child link="${leg_name}_upper_leg" />
            <limit effort="80" velocity="15" lower="-0.89884456477707963539" upper="2.2951079663725435509" />
        </joint>
        
        <link name="${leg_name}_lower_leg">
            <visual>
                <geometry>
                    <mesh filename="package://hector_spot_description/meshes/${leg_name}_lower_leg.dae" />
                </geometry>
            </visual>
            
            <collision>
                <origin xyz="0 0 -${lower_leg_to_foot_z - 0.04 + 0.003}" />
                <geometry>
                    <sphere radius="0.04" />
                </geometry>
            </collision>
            
            <inertial>
                <origin xyz="0 0 -0.16" rpy="0 0 0" />
                <mass value="${lower_leg_mass}"/>
                <inertia ixx="${(1/12) * lower_leg_mass * (lower_leg_width * lower_leg_width + lower_leg_height * lower_leg_height)}" ixy="0.0" ixz="0.0"
                            iyy="${(1/12) * lower_leg_mass * (lower_leg_length * lower_leg_length + lower_leg_height * lower_leg_height)}" iyz="0.0"
                            izz="${(1/12) * lower_leg_mass * (lower_leg_length * lower_leg_length + lower_leg_width * lower_leg_width)}" />     
            </inertial>
        </link>
        
         <gazebo reference="${leg_name}_lower_leg">
            <kp>1e+07</kp>
            <kd>100.0</kd>
            <mu1>0.8</mu1>
            <mu2>0.8</mu2>
<!--            <maxVel>0.0</maxVel>
            <minDepth>0.001</minDepth>-->
        </gazebo>
        
        <joint name="${leg_name}_knee" type="revolute">
            <origin xyz="${upper_leg_to_lower_leg_x} 0 -${upper_leg_to_lower_leg_z}" rpy="0 0 0" />
            <axis xyz="0 1 0" />
            <parent link="${leg_name}_upper_leg" />
            <child link="${leg_name}_lower_leg" />
            <limit effort="80" velocity="15" lower="-2.7929" upper="-0.254801" />
        </joint>
        
        <link name="${leg_name}_ee" />
        
        <joint name="${leg_name}_foot" type="fixed">
            <parent link="${leg_name}_lower_leg" />
            <child link="${leg_name}_ee" />
            <origin xyz="0 0 -${lower_leg_to_foot_z}" rpy="0 0 0" />
        </joint>

        <xacro:joint_standard_transmission name="${leg_name}_hip_x"/>
        <xacro:joint_standard_transmission name="${leg_name}_hip_y"/>
        <xacro:joint_standard_transmission name="${leg_name}_knee"/>
        
    </xacro:macro>
</robot>
