hostname: "192.168.80.3"
app_token_path: "~/.bosdyn/dev.app_token"

frontleft_depth_desired_rate: 1
frontright_depth_desired_rate: 1
left_depth_desired_rate: 1
right_depth_desired_rate: 1
back_depth_desired_rate: 1
